spring:
  profiles:
    active: eng

---

spring:
  profiles: eng

greeting:
  message: Hello! Welcome to Spring World!

---

spring:
  profiles: swe

greeting:
  message: Hej hej! Välkomna till Spring Världen!

---

spring:
  profiles: test
  # ...